### ISSUE TITLE
issues updating data

### ISSUE THREAD

**Issue by ypeskin** [PierreCapo/treeviz#4] opened 2019-02-07 15:34 UTC
Hello,
I get my data file from an ajax call, first time it works great, the second time, the original root stays the same. Am I missing something in my code? Here's relevant code:

<script type="text/javascript" src="~/Scripts/treeviz/index.js"></script>
<script>
  var myTree = Treeviz.create({
    htmlID: "tree",
    nodeField: "MatlItem",
    flatData: false,
    relationnalField: "Children",
    zoomBehavior: true,
    nodeWidth: 120,
    nodeHeight: 75,
    nodeColor: (nodeData) =>"#ffffff",
    horizontalLayout: false,
    linkColor: (nodeData) => "#000000",
    linkShape: "orthogonal",
    linkWidth: (nodeDatat) => 3,
    nodeTemplate: (nodeData) => "<div style='height:75px; width:120px;display:flex;flex-direction:column;justify-content:center;align-items:center;border:2px solid black;'><div><strong>" + nodeData.MatlItem + "</strong></div><div id='innerbox' style='border:2px sold black;'><i>&nbsp;" + /* Number(*/ nodeData.LeadTime /*).toFixed(5) */ + "&nbsp;</i></div></div>"
  });

  function getBom() {
    var item = $("#txtItem").val();
    $("divLoading").show();
    if (item)
    {
      $.ajax({
        cache: false,
        type: 'Get',
        url: '@Url.Action("GetBom")',
        data: { itm: item },
        success: function (data) {
          $("#divLoading").hide();
          if (data.Success == "OK") {
            
            myTree.refresh(data);
          }
          else
          {
            alert(data.Message);
          }
        }

      });
    }
  }

	$(function () {
		$("#tree").width($(document).width()).height($(document).height() - $("#criteria").height());
	});
</script>

**Comment by PierreCapo** [comment] 2019-02-09 12:18
What do you exactly mean by the original root stays the same ? Can you provide a CodePen example to reproduce your issue ?

**Comment by ypeskin** [comment] 2019-02-10 00:00
Hello,I don't know how to use CodePen, but here's a complete explanation:I'm trying to display Bill of Materials for an item. The first time the item (31312-22) is displayed correctly as shown by the 31312-22.png. The second time, when I try to display a different item (43300-22), it displays 31312-22 as the root of the tree, when it should be displaying 43300-22)  as is shown by the 43300-22.png file.I am also getting errors from treeviz on second run, which i did not notice when I originally wrote the e-mail:Error 38: Error: <g> attribute transform: Expected number, "translate(undefined,undefi…".Error 555: Error: <path> attribute d: Expected number, "M NaN undefined\n  …". 
HTH
-- Yury Peskin ypeskin@yahoo.com 

    On Saturday, February 9, 2019, 6:18:38 AM CST, PierreCapo <notifications@github.com> wrote:  
 
 
What do you exactly mean by the original root stays the same ? Can you provide a CodePen example to reproduce your issue ?

**Comment by PierreCapo** [comment] 2019-02-10 11:53
I'm not able to see your images, could you try to edit your previous message and upload it please ?

Anyway I think I've understood what you mean. The issue is that you are building conceptually a new tree (although similar in terms of configuration), whereas a tree should always keep the same root.

I have added a `clean` method which deletes the previous tree and that probably tackle your issue :

```js
const treeConfig = {
  htmlID: "tree",
  nodeField: "MatlItem",
  flatData: false,
  relationnalField: "Children",
  zoomBehavior: true,
  nodeWidth: 120,
  nodeHeight: 75,
  nodeColor: nodeData => "#ffffff",
  horizontalLayout: false,
  linkColor: nodeData => "#000000",
  linkShape: "orthogonal",
  linkWidth: nodeDatat => 3,
  nodeTemplate: nodeData =>
    "" + nodeData.MatlItem + "" + nodeData.LeadTime + " ",
}

let myTree = Treeviz.create(treeConfig);
function getBom() {
  let item = $("#txtItem").val();
  $("divLoading").show();
  if (item) {
    $.ajax({
      cache: false,
      type: "Get",
      url: '@Url.Action("GetBom")',
      data: { itm: item },
      success(data) {
        $("#divLoading").hide();
        if (data.Success == "OK") {
          myTree.clean(); // delete the old tree
          myTree = Treeviz.create(treeConfig); // configure a new tree with the previous same configuration
          myTree.refresh(data); // add the data
        } else {
          alert(data.Message);
        }
      },
    });
  }
}
```

This `clean` method is available only in the `clean-method` branch, before I merge it to master, I'd like to be sure it satisfies your use case. Could you try to download the `index.js` file in this branch and use the code above and tell me if it fits your need ?

**Comment by ypeskin** [comment] 2019-02-10 16:10
Hello,I downloaded the index.js from clean-method branch and replaced the index.js file and made mods to my code, attached bellow and I get the following error when I run the ajax function:
Uncaught TypeError: myTree.clean is not a function    at Object.success (BillOfMaterialsDisplay:128)    at i (jquery-1.12.4.min.js:2)    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js:2)    at y (jquery-1.12.4.min.js:4)    at XMLHttpRequest.c (jquery-1.12.4.min.js:4)
<script src="~/Scripts/treeviz/index.js"></script><script>  $(function () {    $("#divTree").width($(document).width()).height($("#divDetails").height());    console.log("Tree Width: " + $("#divTree").width());    console.log("Tree Height: " + $("#divTree").height());  });
  const treeConfig = {    htmlID: "divTree",    nodeField: "MatlItem",    flatData: false,    relationnalField: "Children",    zoomBehavior: true,    nodeWidth: 120,    nodeHeight: 75,    nodeColor: (nodeData) =>"#ffffff",    horizontalLayout: false,    linkColor: (nodeData) => "#000000",    linkShape: "orthogonal",    linkWidth: (nodeDatat) => 3,    nodeTemplate: (nodeData) => "<div style='height:75px; width:120px;display:flex;flex-direction:column;justify-content:center;align-items:center;border:1 solid black;'>" + nodeData.MatlItem + "<div style='border: 1 solid black;'>" + nodeData.LeadTime + "</div></div>",  }  /* "<div style='height:80px; width:120px;display:flex;flex-direction:column;justify-content:center;align-items:center;'><div><strong>"+nodeData.text_1+"</strong></div><div>is</div><div><i>"+nodeData.text_2+"</i></div></div>" */    let myTree = Treeviz.create(treeConfig);
    function getBom() {      var item = $("#txtItem").val();      $("divLoading").show();      if (item) {        $.ajax({          cache: false,          type: 'Get',          url: '@Url.Action("GetBom")',          data: { itm: item },          success: function (data) {            $("#divLoading").hide();            if (data.Success == "OK") {
              myTree.clean(); // delete the old tree              myTree = Treeviz.create(treeConfig); // configure a new tree with the previous same configuration              myTree.refresh(data);            }            else {              alert(data.Message);            }          }        });      }    }
Thank you for your responsiveness and working with me on this and other issues. Your code is the easiest  to config and use I've seen in a long time.Thanks again,-- Yury Peskin ypeskin@yahoo.com 

    On Sunday, February 10, 2019, 5:53:02 AM CST, PierreCapo <notifications@github.com> wrote:  
 
 
I'm not able to see your images, could you try to edit your previous message and upload it please ?

Anyway I think I've understood what you mean. The issue is that you are building conceptually a new tree (although similar in terms of configuration), whereas a tree should always keep the same root.

I have added a clean method which deletes the previous tree and that probably tackle your issue :
const treeConfig = {
  htmlID: "tree",
  nodeField: "MatlItem",
  flatData: false,
  relationnalField: "Children",
  zoomBehavior: true,
  nodeWidth: 120,
  nodeHeight: 75,
  nodeColor: nodeData => "#ffffff",
  horizontalLayout: false,
  linkColor: nodeData => "#000000",
  linkShape: "orthogonal",
  linkWidth: nodeDatat => 3,
  nodeTemplate: nodeData =>
    "" + nodeData.MatlItem + "" + nodeData.LeadTime + " ",
}

let myTree = Treeviz.create(treeConfig);
function getBom() {
  let item = $("#txtItem").val();
  $("divLoading").show();
  if (item) {
    $.ajax({
      cache: false,
      type: "Get",
      url: '@Url.Action("GetBom")',
      data: { itm: item },
      success(data) {
        $("#divLoading").hide();
        if (data.Success == "OK") {
          myTree.clean(); // delete the old tree
          myTree = Treeviz.create(treeConfig); // configure a new tree with the previous same configuration
          myTree.refresh(data); // add the data
        } else {
          alert(data.Message);
        }
      },
    });
  }
}
This clean method is available only in the clean-method branch, before I merge it to master, I'd like to be sure it satisfies your use case. Could you try to download the index.js file in this branch and use the code above and tell me if it fits your need ?

**Comment by PierreCapo** [comment] 2019-02-10 17:39
If you do `console.log(myTree);` Do you see both `clean` and `refresh` method attached to the object in your console ?

**Comment by ypeskin** [comment] 2019-02-10 17:52
Thanks for responding.



-- Yury Peskin ypeskin@yahoo.com 

    On Sunday, February 10, 2019, 11:39:45 AM CST, PierreCapo <notifications@github.com> wrote:  
 
 
If you do console.log(myTree); Do you see both clean and refresh method attached to the object in your console ?

**Comment by ypeskin** [comment] 2019-02-11 14:54
Hey,
I’ve been trying to figure this issue out all day yesterday and eventually gave up. However, just got to work, and cleaned and rebuilt the solution and the clean function showed up and everything looks like it should. So I would say it’s working.
Thank you again.

Yury Peskin
IT ERP Developer
Standard Iron
524 Pine Street
Monticello, MN. 55362
Yury.Peskin@std-iron.com

**Comment by PierreCapo** [comment] 2019-02-12 14:24
Ok nice to hear that ! I merge it to master and I close the issue so.

**Closed as completed by PierreCapo** 2019-02-12 14:24 UTC
